site_name: "Tri-Contour Dynamics of Limited Resource Allocation (TC)"
site_description: "Tri-Contour Dynamics of Limited Resource Allocation describes how systems allocate limited resources across three competing functional demands: Survival, Reproduction, and Evolution."
site_author: "Viktor Jevdokimov, Vilnius, Lithuania"
copyright: "© 2026 3in3.dev"

docs_dir: docs

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.sections
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search
  - glightbox
#  - to-pdf:
#      output_path: "pdf/tc.pdf"
#      cover_subtitle: "A system model that describes how systems allocate limited resources across three competing functional demands: Survival, Reproduction, and Evolution."
#      toc_level: 3
#      ordered_chapter_level: 3

nav:
- INTRODUCTION:
  - index.md
- THEORY:
  - 110-the-model.md
  - 120-system-structure.md
  - 130-system-dynamics.md
  - 140-system-metabolism.md
  - 150-system-course.md
  - 160-multi-unit-behavior.md
  - 170-application.md
- REFERENCE:
  - origin.md
  - glossary.md
  - author.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true
